config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  use_doorkeeper_openid_connect
  use_doorkeeper
  resources :encrypted_memos
  namespace :admin do
    resources :documents
    resources :users
    resources :announcements
    resources :notifications
    resources :services

    root to: 'users#index'
  end
  namespace :api do
    namespace :v1 do
      resources :users do
        get 'me', on: :collection
      end
    end
  end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  authenticate :user, ->(u) { u.has_role?(:admin_portal) } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :documents
  namespace :users do
    resources :verification_codes, only: [:index]
    resources :login_activities

    get 'directory', to: 'directory#index'
    resources :profiles, only: [:show] do
      resources :roles, only: [:create, :destroy]
    end
  end
  namespace :messages do
    get 'inbox', to: 'inbox#index'
    get 'sent', to: 'sentbox#index'
    resources :conversations do
      post 'reply', on: :member
    end
  end
  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    invitations: 'users/invitations',
    registrations: 'users/registrations'
  }
  get '/go/:id' => "shortener/shortened_urls#show"
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def terms
  end

  def privacy
  end
end

app/views/home/index.html.erb
<div class="jumbotron text-center">
  <%= image_tag 'logo-big.png', width: '450px' %>
  <hr class="my-4">
  <% if current_user %>
  <div class="text-center">
    <h2>
      Welcome, <%= current_user.name %>!

    </h2>
    <hr class="my-4">
    <div class="row">

      <div class="col-md-12">
        <div class="card">
          <h5 class="card-header text-white bg-info">Main Menu</h5>
          <div class="card-body">
            <ul class="list-group">
              <li class="list-group-item disabled bg-secondary text-white">Website under construction</li>
              <% if current_user.has_role?(:admin_portal) %>
              <%= link_to 'Admin Panel', admin_root_path, class: 'list-group-item list-group-item-action list-group-item-secondary' %>
              <% end %>
              <%= link_to 'Secure Documents', documents_path, class: 'list-group-item list-group-item-action' if current_user.has_role?(:document_reader) %>
              <%= link_to 'Encrypted Memos', encrypted_memos_path, class: 'list-group-item list-group-item-action' if current_user.has_role?(:encrypted_memo_viewer) %>
              <%= link_to 'Invite a User', new_user_invitation_path, class: 'list-group-item list-group-item-action list-group-item-warning' if current_user.has_role?(:user_inviter) %>
              <%= link_to 'User Directory', users_directory_path, class: 'list-group-item list-group-item-action list-group-item-warning' if current_user.has_role?(:directory_viewer) %>
              <%= link_to 'Verification Codes', users_verification_codes_path, class: 'list-group-item list-group-item-action list-group-item-warning' if current_user.has_role?(:verifier) %>

            </ul>
            <small class="text-muted">Items highlighted in yellow are special functions available to you as an
              authorized user.</small>
          </div>
        </div>
      </div>
      <!--<div class="col-md-3">
        <div class="card text-white bg-secondary">
          <h5 class="card-header">Your Security Roles</h4>

            <div class="card-body">
              <% if current_user.roles.any? %>
              <ul>
                <% current_user.roles.where(resource_id: nil).each do |role| %>
                <li><%= role.name %></li>
                <% end %>
              </ul>
              <% else %>
              <p>You have not been assigned to any security roles.</p>
              <% end %>
            </div>
        </div>

      </div>-->
    </div>
  </div>
  <% else %>
  <p class="lead">
    Please sign in to access this secure resource.
    <br>
    <%= link_to 'Sign in', new_user_session_path, class: 'btn btn-success btn-lg' %>
  </p>
  <% end %>
</div>
<div class="text-center" data-controller="hello">
  <code data-target="hello.output"></code>
</div>

app/views/home/privacy.html.erb
<p class="lead">
  <%= link_to 'Click here', 'https://app.termly.io/document/privacy-policy/7e815009-4cc9-46bc-a275-d445469ad83f', target: '_blank' %>
  to view our privacy policy.
</p>

app/views/home/terms.html.erb
<h1>Terms of Service</h1>
<p class="lead">Use this for your Terms of Service</p>