config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  use_doorkeeper_openid_connect
  use_doorkeeper
  resources :encrypted_memos
  namespace :admin do
    resources :documents
    resources :users
    resources :announcements
    resources :notifications
    resources :services

    root to: 'users#index'
  end
  namespace :api do
    namespace :v1 do
      resources :users do
        get 'me', on: :collection
      end
    end
  end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  authenticate :user, ->(u) { u.has_role?(:admin_portal) } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :documents
  namespace :users do
    resources :verification_codes, only: [:index]
    resources :login_activities

    get 'directory', to: 'directory#index'
    resources :profiles, only: [:show] do
      resources :roles, only: [:create, :destroy]
    end
  end
  namespace :messages do
    get 'inbox', to: 'inbox#index'
    get 'sent', to: 'sentbox#index'
    resources :conversations do
      post 'reply', on: :member
    end
  end
  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    invitations: 'users/invitations',
    registrations: 'users/registrations'
  }
  get '/go/:id' => "shortener/shortened_urls#show"
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/document.rb
class Document < ApplicationRecord
  resourcify
  belongs_to :attachable, polymorphic: true, optional: true
  has_secure_token
  has_one_attached :download
  before_create :set_default_attachable
  after_create :set_viewers

  attribute :viewers, :string, array: true

  private

  def set_default_attachable
    self.attachable_id ||= 0
    self.attachable_type ||= 'User'
  end

  def set_viewers
    if viewers.size > 0
      viewers.each do |viewer|
        next if viewer.empty?
        user = User.find(viewer)
        user.add_role(:viewer, self)
      end
    end
  end
end

app/controllers/admin/documents_controller.rb
module Admin
  class DocumentsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_document, only: [:show]
  def index
    @documents = DocumentDecorator.decorate_collection(policy_scope(Document))
    #authorize @documents
  end

  def show
  end

  def new
    @document = Document.new
    authorize @document
  end

  def create
    @document = Document.new(document_params)
    authorize @document
    @document.attachable = current_user
    if @document.save
      redirect_to @document, notice: 'Document created successfully.'
    else
      render :new
    end
  end

  private

  def set_document
    @document = DocumentDecorator.decorate(policy_scope(Document).find(params[:id]))
    #authorize @document
  end

  def document_params
    params.require(:document).permit(:title, :description, :download, viewers: [])
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/index.html.erb
<h1>Secure Documents</h1>
<div class="alert alert-warning">
  <strong>These documents require privileged access.</strong> Please do not share these documents or your login
  credentials with others.
</div>
<% if current_user.has_role?(:document_creator) %>
<div class="actions">
  <%= link_to 'Add New Document', new_document_path, class: 'btn btn-sm btn-success' %>
</div>

<% end %>
<table class="table table-condensed table-bordered table-striped table-hover">
  <thead>
    <tr>
      <th>Date published</th>
      <th>Document Title</th>
      <th>Description</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @documents.each do |document| %>
    <tr>
      <td><%= document.created_at %></td>
      <td><%= document.title %></td>
      <td><%= truncate document.description, length: 25 %></td>
      <td><%= link_to 'View', document %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/documents/new.html.erb
<div class="card">
  <h4 class="card-header">Add a Secure Document</h4>
  <div class="card-body">
    <%= form_with model: @document, local: true do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :download, 'File' %>
      <%= f.file_field :download, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :viewers %>
      <%= f.collection_select :viewers, User.all, :id, :email, {}, {multiple: true} %>
    </div>
    <div class="form-group">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
    <% end %>
  </div>
</div>

app/views/documents/show.html.erb
<div class="card">
  <h4 class="card-header">Secure Document</h4>
  <div class="card-body">
    <dl>
      <dt>Filename</dt>
      <dd>
        <%= @document.download.attached? ? link_to(@document.download.filename, url_for(@document.download), target: '_blank') : 'No file attached' %>
        <br>
        <div class="small">Click to Download</div>
      </dd>
      <dt>Description</dt>
      <dd><%= @document.description %></dd>
    </dl>
    <% if current_user.has_role?(:document_creator) %>
    <div class="access-list">
      <h4>Users with access:</h4>
      <ul>
        <% User.with_role(:viewer, Document.find(@document.id)).each do |u| %>
        <li><%= u.email %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
  </div>
</div>